/**
 * Device API Module
 * 
 * Provides API functions for device management:
 * - GET /api/devices - Get all user devices
 * - DELETE /api/devices/:id - Remove device
 * - PATCH /api/devices/:id - Update device name
 * 
 * @module devices/api
 */

import { getAccessToken } from '../auth/tokens';
import type {
  DeleteDeviceResponse,
  Device,
  DevicesResponse,
  PendingVerificationsResponse,
  UpdateDeviceNameRequest,
  UpdateDeviceResponse,
  VerificationCodeResponse,
  VerifyDeviceResponse,
} from './types';
import { DeviceError } from './types';
import { argon2id } from '@noble/hashes/argon2.js';

// Fixed salt for verification code hashing (must be same on all devices)
// Generated by scripts/generate_verification_salt.py
export const VERIFICATION_SALT = new Uint8Array([
  0x31, 0xb5, 0x59, 0x86, 0xa7, 0x8f, 0x58, 0x8d,
  0x47, 0x66, 0xa5, 0x9b, 0x4c, 0xb6, 0xe3, 0x56
]);

export function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
}

// ==================== Configuration ====================

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001/api';

// ==================== Request Helper ====================

/**
 * Make authenticated API request
 */
async function request<T>(
  endpoint: string,
  options: RequestInit = {}
): Promise<T> {
  const url = `${API_BASE_URL}${endpoint}`;
  const token = getAccessToken();

  // Не устанавливаем Content-Type для запросов без тела (DELETE, GET и т.д.)
  // Fastify отклоняет пустое тело с Content-Type: application/json
  const hasBody = options.body !== undefined && options.body !== null;
  const headers: Record<string, string> = {
    ...(hasBody ? { 'Content-Type': 'application/json' } : {}),
    ...((options.headers as Record<string, string>) || {}),
  };

  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  try {
    const response = await fetch(url, {
      ...options,
      headers,
      credentials: 'include',
    });

    if (!response.ok) {
      throw await handleError(response);
    }

    const text = await response.text();
    return text ? JSON.parse(text) : ({} as T);
  } catch (error) {
    if (error instanceof DeviceError) throw error;
    if (error instanceof TypeError && error.message.includes('fetch')) {
      throw new DeviceError(
        'Ошибка сети. Проверьте соединение.',
        'NETWORK_ERROR'
      );
    }
    throw error;
  }
}

/**
 * Handle HTTP error response
 */
async function handleError(response: Response): Promise<DeviceError> {
  const statusCode = response.status;
  let message = 'Произошла ошибка';
  let code = 'UNKNOWN_ERROR';
  let retryAfter: number | undefined = undefined;

  try {
    const errorData = await response.json();
    message = errorData.detail || errorData.title || errorData.message || message;
    code = errorData.type?.split('/').pop() || code;
    
    // Проверяем retryAfter из ответа
    if (errorData.retryAfter) {
      retryAfter = errorData.retryAfter;
    }
  } catch {
    const errorMessages: Record<number, { message: string; code: string }> = {
      400: { message: 'Неверный запрос.', code: 'BAD_REQUEST' },
      401: { message: 'Не авторизован.', code: 'UNAUTHORIZED' },
      403: { message: 'Доступ запрещён.', code: 'FORBIDDEN' },
      404: { message: 'Устройство не найдено.', code: 'NOT_FOUND' },
      429: { message: 'Слишком много запросов. Попробуйте позже.', code: 'RATE_LIMITED' },
      500: { message: 'Ошибка сервера.', code: 'INTERNAL_ERROR' },
    };

    const mapped = errorMessages[statusCode];
    if (mapped) {
      message = mapped.message;
      code = mapped.code;
    }
  }

  // Если есть retryAfter, добавляем его в сообщение
  if (retryAfter !== undefined && statusCode === 429) {
    message = `${message} Повторите через ${retryAfter} сек.`;
  }

  return new DeviceError(message, code, statusCode);
}

// ==================== Device API ====================

/**
 * Get all user devices
 * 
 * @returns List of devices with current device ID
 * @example
 * const { devices, current_device_id } = await getDevices();
 */
export async function getDevices(): Promise<DevicesResponse> {
  return request<DevicesResponse>('/devices');
}

/**
 * Delete a device (sign out from device)
 * 
 * @param deviceId - Device ID to remove
 * @throws DeviceError if deletion fails
 * @example
 * await removeDevice('device-uuid');
 */
export async function removeDevice(deviceId: string): Promise<DeleteDeviceResponse> {
  return request<DeleteDeviceResponse>(`/devices/${deviceId}`, {
    method: 'DELETE',
  });
}

/**
 * Update device name
 * 
 * @param deviceId - Device ID to update
 * @param name - New device name (1-50 characters)
 * @returns Updated device data
 * @throws DeviceError if update fails
 * @example
 * const { device } = await updateDeviceName('device-uuid', 'My iPhone');
 */
export async function updateDeviceName(
  deviceId: string,
  name: string
): Promise<UpdateDeviceResponse> {
  const body: UpdateDeviceNameRequest = { name };
  
  return request<UpdateDeviceResponse>(`/devices/${deviceId}`, {
    method: 'PATCH',
    body: JSON.stringify(body),
  });
}

/**
 * Generate verification code for a device
 * 
 * @param deviceId - Device ID to generate code for
 * @returns Verification code and expiration time
 * @throws DeviceError if generation fails
 */
export async function generateVerificationCode(deviceId: string): Promise<VerificationCodeResponse> {
  console.log('[devices/api] generateVerificationCode called with deviceId:', deviceId);
  const url = `/devices/${deviceId}/verification-code`;
  console.log('[devices/api] Request URL:', url);
  return request<VerificationCodeResponse>(url, {
    method: 'POST',
  });
}

/**
 * Verify device with code
 * 
 * @param deviceId - Device ID to verify
 * @param code - 6-digit verification code
 * @returns Verification result
 * @throws DeviceError if verification fails
 */
export async function verifyDevice(
  deviceId: string,
  code: string
): Promise<VerifyDeviceResponse> {
  // Compute Argon2id hash of the code using @noble/hashes
  const password = new TextEncoder().encode(code);
  const hash = argon2id(password, VERIFICATION_SALT, {
    t: 3,
    m: 65536,
    p: 1,
    dkLen: 32,
    maxmem: 2 ** 32 - 1
  });
  const codeHash = bytesToHex(hash);

  return request<VerifyDeviceResponse>(`/devices/${deviceId}/verify`, {
    method: 'POST',
    body: JSON.stringify({ codeHash }),
  });
}

/**
 * Get pending verifications
 * 
 * @returns List of devices waiting for verification
 * @throws DeviceError if request fails
 */
export async function getPendingVerifications(): Promise<PendingVerificationsResponse> {
  return request<PendingVerificationsResponse>('/devices/pending-verifications');
}

/**
 * Confirm verification code from a verified device
 * 
 * @param deviceId - Verified device ID (the one sending the code)
 * @param codeHash - Argon2id hash of the 6-digit code
 * @param newDeviceId - New device ID that requested verification
 * @returns Success status
 * @throws DeviceError if confirmation fails
 */
export async function confirmVerificationCode(
  deviceId: string,
  codeHash: string,
  newDeviceId: string
): Promise<{ success: boolean }> {
  return request<{ success: boolean }>(`/devices/${deviceId}/verification-code/confirm`, {
    method: 'POST',
    body: JSON.stringify({ codeHash, newDeviceId }),
  });
}

// ==================== Exports ====================

export type {
  DeleteDeviceResponse,
  Device,
  DevicesResponse,
  PendingVerification,
  PendingVerificationsResponse,
  UpdateDeviceNameRequest,
  UpdateDeviceResponse,
  VerificationCodeResponse,
  VerifyDeviceResponse,
} from './types';
export { DeviceError } from './types';
