/**
 * WebSocketContext - WebSocket connection management
 * Provides WebSocket connection state and methods to React components
 * 
 * Supports two modes:
 * - Direct WebSocket (default) - each tab has its own connection
 * - Shared Worker - single connection shared across all tabs
 */

import type React from 'react';
import { createContext, useCallback, useContext, useEffect, useMemo,useRef, useState } from 'react';

import { toast } from '@/components/ui/toast';
import type { PreKeyBundle } from '@/lib/signal/types';
import type { P2PSyncManager} from '@/lib/sync';
import { createP2PSyncManager, type SyncStatus } from '@/lib/sync';
import { base64ToUint8Array, uint8ArrayToBase64 } from '@/lib/utils/buffer';
import type {
  // Shared Worker support
  WorkerWebSocketClient} from '@/lib/websocket';
import {
  type ConnectionState,
  createWorkerClient,
  DEFAULT_WS_CONFIG,
  shouldUseSharedWorker,
  type WebSocketClientInterface,
  WebSocketConnection,
} from '@/lib/websocket';
import { getAccessToken, isTokenExpired,refreshTokens } from '@/services/auth';
 import { chatService } from '@/services/chat';
 import { storeMessage, type StoredMessage, incrementUnreadCount } from '@/lib/messages';
 import { confirmVerificationCode } from '@/services/devices/api';
import type {
  WSMessageStatusPayload,
  WSNewMessagePayload,
} from '@/types';
 import type {
   WSDeviceOnlinePayload,
   WSPresenceUpdatePayload,
   WSReadAckPayload,
   WSReadEventPayload,
   WSSyncAcceptPayload,
   WSSyncCancelPayload,
   WSSyncHistoryPayload,
   WSSyncInvitePayload,
   WSSyncRejectPayload,
   WSSyncRequestPayload,
   WSAttachment,
   WSMessage,
 } from '@/types/websocket';
   import { createCommandBus, type CommandBus } from '@/lib/command-bus';
   import { argon2id } from '@noble/hashes/argon2.js';

// Fixed salt for verification code hashing (must match api.ts)
// Generated by scripts/generate_verification_salt.py
const VERIFICATION_SALT = new Uint8Array([
  0x31, 0xb5, 0x59, 0x86, 0xa7, 0x8f, 0x58, 0x8d,
  0x47, 0x66, 0xa5, 0x9b, 0x4c, 0xb6, 0xe3, 0x56
]);

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
}

// Storage key for system chat ID
const SYSTEM_CHAT_ID_KEY = 'system-chat-id';

 import { useAuth } from './AuthContext';
 import { useSignal } from './SignalContext';
 import { useQueryClient } from '@tanstack/react-query';
 import { queryKeys } from '@/queries';
 import { useUnreadStore } from '@/stores';

// ==================== Types ====================

export type MessageHandler = (data: unknown) => void;

export interface WebSocketContextType {
  isConnected: boolean;
  isConnecting: boolean;
  connect: () => Promise<void>;
  disconnect: () => void;
  send: (type: string, payload: unknown) => Promise<void>;
  subscribe: (type: string, handler: MessageHandler) => () => void;
  sendTyping: (chatId: string, isTyping: boolean) => void;
  sendMarkRead: (chatId: string, messageIds?: string[]) => void;
    sendMultiDeviceMessage: (
       chatId: string,
       recipientId: string,
       recipientMessages: { deviceId: number; content: string; messageType: number }[],
       senderMessages?: { deviceId: number; content: string; messageType: number }[],
       attachments?: WSAttachment[],
       replyTo?: string,
       metadata?: Record<string, any>
     ) => Promise<string>;
    sendGroupMessage: (
      chatId: string,
      senderUserId: string,
      senderDeviceId: string,
      content: string,
      messageId?: string,
      senderKeyId?: string,
      replyTo?: string,
      attachments?: WSAttachment[],
      senderKeyDistribution?: string,
      metadata?: Record<string, any>
    ) => Promise<string>;
  sendSessionSync: (userId: string, deviceId: number, reason: 'session_refresh' | 'new_device' | 'retry_request') => void;
  sendMessageRetryRequest: (originalMessageId: string, chatId: string, senderId: string, senderDeviceId: number) => void;
  // Event subscriptions
  onMessage: (callback: (data: unknown) => void) => () => void;
  onNewMessage: (callback: (data: WSNewMessagePayload) => void) => () => void;
  onMessageDelivered: (callback: (data: WSMessageStatusPayload) => void) => () => void;
  onMessageRead: (callback: (data: WSMessageStatusPayload) => void) => () => void;
  onUserOnline: (callback: (data: { userId: string }) => void) => () => void;
  onUserOffline: (callback: (data: { userId: string }) => void) => () => void;
  onSessionSync: (callback: (data: { userId: string; deviceId: number; reason: string }) => void) => () => void;
  onMessageRetry: (callback: (data: { originalMessageId: string; chatId: string; senderId: string; senderDeviceId: number }) => void) => () => void;
  onReadEvent: (callback: (data: WSReadEventPayload) => void) => () => void;
  onReadAck: (callback: (data: WSReadAckPayload) => void) => () => void;
  onPresence: (callback: (data: WSPresenceUpdatePayload) => void) => () => void;
  // P2P Sync
  p2pSyncManager: P2PSyncManager | null;
  syncStatus: SyncStatus;
  requestSync: () => Promise<void>;
  onSyncRequest: (callback: (data: WSSyncRequestPayload) => void) => () => void;
  onSyncHistory: (callback: (data: WSSyncHistoryPayload) => void) => () => void;
  onDeviceOnline: (callback: (data: WSDeviceOnlinePayload) => void) => () => void;
  // Two-phase sync events
  onSyncInvite: (callback: (data: WSSyncInvitePayload) => void) => () => void;
  onSyncAccept: (callback: (data: WSSyncAcceptPayload) => void) => () => void;
  onSyncCancel: (callback: (data: WSSyncCancelPayload) => void) => () => void;
  onSyncReject: (callback: (data: WSSyncRejectPayload) => void) => () => void;
  // Command Bus
  commandBus: CommandBus | null;
}

// ==================== Context ====================

const WebSocketContext = createContext<WebSocketContextType | null>(null);

// ==================== Provider ====================

 export function WebSocketProvider({
   children,
   onConnect,
   onDisconnect,
 }: {
   children: React.ReactNode;
   onConnect?: () => void;
   onDisconnect?: () => void;
 }) {
   const { isAuthenticated, user } = useAuth();
   const signal = useSignal();
   const isSignalReady = signal.isInitialized;
   const getSignalDeviceId = signal.getDeviceId;
   const queryClient = useQueryClient();
  // Build WebSocket URL from current page location or use env variable
  const wsUrl = useMemo(() => {
    const envUrl = import.meta.env.VITE_WS_URL;
    if (envUrl) {
      // If env URL is relative, build absolute URL from current location
      if (envUrl.startsWith('/')) {
        const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
        return `${protocol}//${window.location.host}${envUrl}`;
      }
      return envUrl;
    }
    // Fallback to default
    return 'ws://localhost:3001/ws';
  }, []);

  // Determine if we should use Shared Worker mode
  const useWorker = useMemo(() => shouldUseSharedWorker(), []);

  // Get device ID from localStorage
  const getDeviceUuid = useCallback(() => localStorage.getItem('device-id'), []);

  // WebSocket connection instance (singleton) - for direct mode
  const wsRef = useRef<WebSocketConnection | null>(null);
  
  // Worker client instance - for Shared Worker mode
  const workerRef = useRef<WorkerWebSocketClient | null>(null);

  // P2P Sync Manager
  const p2pSyncRef = useRef<P2PSyncManager | null>(null);

  // Connection state
  const [state, setState] = useState<ConnectionState>({
    isConnected: false,
    isConnecting: false,
    lastError: null,
    reconnectAttempts: 0,
  });

  // Sync status state
  const [syncStatus, setSyncStatus] = useState<SyncStatus>({
    isSyncing: false,
    lastSyncAt: null,
    error: null,
    vectorClock: {},
    invitePhase: 'idle',
    transferProgress: null,
    transferPhase: 'idle',
  });

  // Command Bus state
  const [commandBus, setCommandBus] = useState<CommandBus | null>(null);
  const commandBusRef = useRef<CommandBus | null>(null);

  // Store unsubscribe functions
  const unsubsRef = useRef<(() => void)[]>([]);
  
  // Flag to prevent multiple invite attempts
  const inviteSentRef = useRef(false);

  // Initialize WebSocket connection instance (direct mode only)
  const wsInstance = useMemo(() => {
    if (useWorker || wsRef.current) return null;
    return new WebSocketConnection({
      ...DEFAULT_WS_CONFIG,
      url: wsUrl,
      token: getAccessToken() || '',
      getToken: async () => {
        let token = localStorage.getItem('access-token') || '';
        if (!token || isTokenExpired(token)) {
          try {
            await refreshTokens();
            token = localStorage.getItem('access-token') || '';
          } catch (error) {
            // Return whatever we have - will fail with 4002 and trigger logout
          }
        }
        return token;
      },
    });
  }, [useWorker, wsUrl]);

  if (!useWorker && !wsRef.current && wsInstance) {
    wsRef.current = wsInstance;
  }

  // Initialize Worker client (Shared Worker mode only)
  if (useWorker && !workerRef.current) {
    workerRef.current = createWorkerClient();
  }

  // Get the appropriate connection object based on mode
  const ws: WebSocketClientInterface = useWorker ? workerRef.current! : wsRef.current!;

  // Шаг 1 / Шаг 5 — Auto-connect WS when auth + Signal are ready.
  //
  // CRITICAL: prior to this change, nothing in the app actually called
  // `ws.connect()`. The WebSocketConnection / WorkerWebSocketClient were
  // constructed but never opened a socket, so the app ran without any
  // real-time transport. This effect triggers the connection as soon as
  // the user is authenticated AND Signal is initialized (Signal-Not-Ready
  // close codes would otherwise bounce the WS immediately).
  //
  // Both connect() implementations are idempotent (guarded against
  // double-connect), so re-running this effect on unrelated re-renders
  // is safe.
  useEffect(() => {
    if (!isAuthenticated || !user || !isSignalReady) {
      return;
    }
    const token = getAccessToken();
    if (!token) {
      return;
    }

    if (useWorker && workerRef.current) {
      // WorkerWebSocketClient.connect(url, token) — sends 'connect' command
      // to the SharedWorker which opens a single WS for the whole browser.
      workerRef.current.connect(wsUrl, token);
    } else if (!useWorker && wsRef.current) {
      // WebSocketConnection.connect(url?, token?) — updates config.url and
      // config.token if args are provided, then opens the socket.
      void wsRef.current.connect(wsUrl, token);
    }
    // No cleanup here — disconnect is handled by the dedicated effect below
    // so we don't tear down the connection on every dep change.
  }, [isAuthenticated, user, isSignalReady, wsUrl, useWorker]);

  // Шаг 5 — Disconnect on logout / unmount.
  useEffect(() => {
    if (!isAuthenticated) {
      // Direct mode: WebSocketConnection.disconnect() closes the socket,
      // stops heartbeat/reconnect, and removes all event listeners.
      // Worker mode: WorkerWebSocketClient.disconnect() sends 'disconnect'
      // to the worker (which closes the shared WS only if no other tabs
      // remain) and tears down this tab's MessagePort.
      if (useWorker && workerRef.current) {
        workerRef.current.disconnect();
      } else if (!useWorker && wsRef.current) {
        wsRef.current.disconnect();
      }
    }
  }, [isAuthenticated, useWorker]);

  // Шаг 5 — Token refresh handling.
  //
  // When the JWT is refreshed (proactively or reactively), push the new
  // token to the SharedWorker so it can reconnect with it if the WS drops.
  // Direct mode picks up the new token via the `getToken()` callback that
  // WebSocketConnection already calls on every reconnect attempt, so it
  // needs no extra wiring here.
  //
  // We use TWO listeners:
  //   1. BroadcastChannel('auth:token-refresh') — fires in OTHER tabs
  //      (TokenRefreshManager skips same-tab events via sourceTabId).
  //   2. window 'storage' event on 'access-token' — also cross-tab but
  //      works even if BroadcastChannel is unavailable.
  //   3. Polling fallback for SAME-tab refresh (TokenRefreshManager runs
  //      in-process in the current tab and doesn't dispatch a same-tab
  //      event we can hook into without editing AuthContext, which is
  //      outside this agent's ownership). The poll is cheap (just reads
  //      localStorage + compares to last-seen value) and runs every 15s.
  const lastPushedTokenRef = useRef<string | null>(null);
  useEffect(() => {
    if (!useWorker) {
      return;
    }
    const pushToken = (token: string) => {
      if (!token || token === lastPushedTokenRef.current) return;
      lastPushedTokenRef.current = token;
      workerRef.current?.updateToken(token);
    };

    // Initial push
    const initial = getAccessToken();
    if (initial) pushToken(initial);

    // 1. BroadcastChannel
    let bc: BroadcastChannel | null = null;
    try {
      bc = new BroadcastChannel('auth:token-refresh');
      bc.onmessage = (event: MessageEvent) => {
        const data = event.data as
          | { type?: string; payload?: { newToken?: string } }
          | undefined;
        if (data?.type === 'auth:token-refreshed' && data.payload?.newToken) {
          pushToken(data.payload.newToken);
        }
      };
    } catch {
      bc = null;
    }

    // 2. window 'storage' event
    const onStorage = (event: StorageEvent) => {
      if (event.key === 'access-token' && event.newValue) {
        pushToken(event.newValue);
      }
    };
    window.addEventListener('storage', onStorage);

    // 3. Same-tab polling fallback
    const interval = setInterval(() => {
      const t = getAccessToken();
      if (t) pushToken(t);
    }, 15000);

    return () => {
      bc?.close();
      window.removeEventListener('storage', onStorage);
      clearInterval(interval);
    };
  }, [useWorker]);

  // Шаг 5 — Cleanup on full unmount of WebSocketProvider.
  //
  // Uses an empty dep array so the cleanup runs only when the provider is
  // actually unmounted (not on every dep change). We intentionally do NOT
  // call ws.disconnect() here for worker mode: another tab might still be
  // using the SharedWorker. The SharedWorker internally cleans itself up
  // when `tabs.size === 0`. For direct mode we DO tear down the WS since
  // it's tab-local.
  useEffect(() => {
    return () => {
      // Drain unsubscribe callbacks accumulated during the lifetime of
      // this provider (P2P sync, command bus, event subscriptions).
      while (unsubsRef.current.length > 0) {
        const unsub = unsubsRef.current.pop();
        try {
          unsub?.();
        } catch {
          /* ignore */
        }
      }
      if (!useWorker && wsRef.current) {
        try {
          wsRef.current.disconnect();
        } catch {
          /* ignore */
        }
      }
      // Worker mode: do NOT destroy the singleton SharedWorker — other
      // tabs may still be using it. WorkerWebSocketClient.disconnect()
      // would also tear down this tab's MessagePort, but React unmount
      // of the provider only happens on full app teardown, where leaving
      // a dangling MessagePort is harmless (the browser GC will close
      // it). Avoiding disconnect here prevents accidental closure of
      // the shared WS during HMR / StrictMode double-mount in dev.
    };
  }, [useWorker]);

   // Initialize P2P Sync Manager
   useEffect(() => {
     const deviceUuid = getDeviceUuid();
     if (user && deviceUuid && isSignalReady && !p2pSyncRef.current) {
       /**
        * Fetch PreKeyBundle for another device of the same user
        * This is needed to establish Signal Protocol sessions between devices
        */
       const fetchPreKeyBundle = async (userId: string, deviceId: number): Promise<PreKeyBundle | null> => {
         try {
           const response = await chatService.getPreKeyBundle(userId, String(deviceId));
           
           // Convert server response to PreKeyBundle format expected by Signal Protocol
           const bundle: PreKeyBundle = {
             registrationId: response.registrationId,
             deviceId: deviceId,
             identityKey: base64ToUint8Array(response.identityKeyPub),
             signedPreKeyId: response.signedPreKey.id,
             signedPreKey: base64ToUint8Array(response.signedPreKey.pub),
             signedPreKeySignature: base64ToUint8Array(response.signedPreKey.sig),
             preKeyId: response.oneTimeEcPreKey?.id,
             preKey: response.oneTimeEcPreKey ? base64ToUint8Array(response.oneTimeEcPreKey.pub) : undefined,
             kyberPreKeyId: response.oneTimePqPreKey?.id ?? response.pqLastResortPreKey?.id,
             kyberPreKey: response.oneTimePqPreKey 
               ? base64ToUint8Array(response.oneTimePqPreKey.pub) 
               : response.pqLastResortPreKey 
                 ? base64ToUint8Array(response.pqLastResortPreKey.pub) 
                 : undefined,
             kyberPreKeySignature: response.oneTimePqPreKey?.sig 
               ? base64ToUint8Array(response.oneTimePqPreKey.sig)
               : response.pqLastResortPreKey?.sig
                 ? base64ToUint8Array(response.pqLastResortPreKey.sig)
                 : undefined,
           };
           
           return bundle;
         } catch (error) {
           return null;
         }
       };

       p2pSyncRef.current = createP2PSyncManager({
         send: async (type, payload) => {
           await ws.sendMessage({ type, payload } as Parameters<typeof ws.sendMessage>[0]);
         },
         deviceId: deviceUuid,
         userId: user.id,
         getSignalDeviceId,
         fetchPreKeyBundle,
       });

       // Subscribe to sync status changes
       const unsub = p2pSyncRef.current.subscribeToStatus(setSyncStatus);
       unsubsRef.current.push(unsub);
     }
   }, [user, getDeviceUuid, isSignalReady, ws, getSignalDeviceId]);

   // Initialize Command Bus
   useEffect(() => {
     if (!ws || !isSignalReady || !user || commandBusRef.current) {
       return;
     }
       const bus = createCommandBus(
         { maxRetries: 3, baseDelayMs: 1000 },
         {
           wsSend: (msg) => {
             ws.sendMessage({
               type: msg.type,
               payload: msg.payload
             } as Parameters<typeof ws.sendMessage>[0]);
           },
           encrypt: async (recipientId, recipientDeviceId, message) => {
             const result = await signal.encrypt(recipientId, recipientDeviceId, message);
             return {
               body: uint8ArrayToBase64(result.body), // Convert Uint8Array to base64 string
               type: result.type
             };
           },
           decrypt: async (senderId, senderDeviceId, message, messageType) => {
             // message is Uint8Array (already converted from base64 by command-bus)
             return await signal.decrypt(senderId, senderDeviceId, message, messageType);
           },
           getCurrentUserId: () => user.id,
           getCurrentDeviceId: () => localStorage.getItem('device-id') || '',
           getSignalDeviceId: () => signal.getDeviceId(),
         }
       );
       
       commandBusRef.current = bus;
       setCommandBus(bus);

       // Subscribe to WebSocket command events
       const unsubAck = ws.on('command_ack', (data: unknown) => {
         bus.handleCommandAck(data as Record<string, unknown>);
       });
       const unsubEvent = ws.on('command_event', (data: unknown) => {
         bus.handleCommandEvent(data as Record<string, unknown>);
       });
       const unsubError = ws.on('command_error', (data: unknown) => {
         bus.handleCommandError(data as Record<string, unknown>);
       });

       const unsubs = [unsubAck, unsubEvent, unsubError];
       unsubs.forEach(unsub => unsubsRef.current.push(unsub));

       // Global handler for device verification request
        const unsubVerification = bus.on(async (event) => {
          if (event.commandType === 'device.verification_request') {
            try {
              const { payload } = event;
              const verificationPayload = payload as { newDeviceId: string; newDeviceName: string };

              if (!user) {
                console.error('[WebSocketContext] No user, cannot process verification request');
                return;
              }

              const currentDeviceId = localStorage.getItem('device-id');
              if (!currentDeviceId) {
                console.error('[WebSocketContext] No device-id in localStorage');
                return;
              }

              const signalDeviceId = signal.getDeviceId();
              if (signalDeviceId === null) {
                console.error('[WebSocketContext] No signal device id');
                return;
              }

              // Generate 6-digit code
              const code = Math.floor(100000 + Math.random() * 900000).toString();

              // Hash with Argon2id
              const password = new TextEncoder().encode(code);
              const hash = argon2id(password, VERIFICATION_SALT, {
                t: 3,
                m: 65536,
                p: 1,
                dkLen: 32,
                maxmem: 2 ** 32 - 1,
              });
              const codeHash = bytesToHex(hash);

              // Store hash on backend
              try {
                await confirmVerificationCode(currentDeviceId, codeHash, verificationPayload.newDeviceId);
              } catch (error) {
                console.error('[Verification] Failed to confirm verification code:', error);
                throw error;
              }
            } catch (error) {
              console.error('[Verification] Failed to handle verification request:', error);
            }
          }
        });

      unsubsRef.current.push(unsubVerification);

      return () => {
        unsubVerification();
      };
   }, [ws.isConnected, ws, storeMessage, queryClient]);

  // Send message
  const send = useCallback(async (type: string, payload: unknown): Promise<void> => {
    await ws.sendMessage({ type, payload } as Parameters<typeof ws.sendMessage>[0]);
  }, [ws]);

  // Subscribe to events
  const subscribe = useCallback((type: string, handler: MessageHandler): (() => void) => {
    const unsub = ws.on(type, handler);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  // Event subscription helpers
  const onMessage = useCallback((callback: (data: unknown) => void) => {
    const unsub = ws.onMessage(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  // Expose connect/disconnect so callers (e.g. UI buttons) can manage
  // the WebSocket lifecycle. The underlying WebSocketClient interface
  // may or may not implement these; fall back to no-op if absent.
  const connect = useCallback(async (): Promise<void> => {
    if (typeof (ws as any).connect === 'function') {
      return (ws as any).connect();
    }
  }, [ws]);

  const disconnect = useCallback((): void => {
    if (typeof (ws as any).disconnect === 'function') {
      (ws as any).disconnect();
    }
  }, [ws]);

  const onNewMessage = useCallback((callback: (data: WSNewMessagePayload) => void) => {
    const unsub = ws.onNewMessage(callback as (data: unknown) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onMessageDelivered = useCallback((callback: (data: WSMessageStatusPayload) => void) => {
    const unsub = ws.onMessageDelivered(callback as (data: unknown) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onMessageRead = useCallback((callback: (data: WSMessageStatusPayload) => void) => {
    const unsub = ws.onMessageRead(callback as (data: unknown) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onUserOnline = useCallback((callback: (data: { userId: string }) => void) => {
    const unsub = ws.onUserOnline(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onUserOffline = useCallback((callback: (data: { userId: string }) => void) => {
    const unsub = ws.onUserOffline(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onSessionSync = useCallback((callback: (data: { userId: string; deviceId: number; reason: string }) => void) => {
    const unsub = ws.onSessionSync(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onMessageRetry = useCallback((callback: (data: { originalMessageId: string; chatId: string; senderId: string; senderDeviceId: number }) => void) => {
    const unsub = ws.onMessageRetry(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onReadEvent = useCallback((callback: (data: WSReadEventPayload) => void) => {
    const unsub = ws.onReadEvent(callback as (data: unknown) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onReadAck = useCallback((callback: (data: WSReadAckPayload) => void) => {
    const unsub = ws.onReadAck(callback as (data: unknown) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onPresence = useCallback((callback: (data: WSPresenceUpdatePayload) => void) => {
    const unsub = ws.onPresence(callback as (data: { userId: string; status: 'online' | 'offline' }) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  // P2P Sync handlers
  const requestSync = useCallback(async () => {
    if (p2pSyncRef.current) {
      await p2pSyncRef.current.requestHistory();
    }
  }, []);

  const onSyncRequest = useCallback((callback: (data: WSSyncRequestPayload) => void) => {
    const unsub = ws.onSyncRequest(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onSyncHistory = useCallback((callback: (data: WSSyncHistoryPayload) => void) => {
    const unsub = ws.onSyncHistory(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onDeviceOnline = useCallback((callback: (data: WSDeviceOnlinePayload) => void) => {
    const unsub = ws.onDeviceOnline(callback);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  // Two-phase sync event handlers
  const onSyncInvite = useCallback((callback: (data: WSSyncInvitePayload) => void) => {
    const unsub = ws.onSyncInvite(callback as (data: { invitingDeviceId: string; invitingDeviceName?: string; timestamp: number }) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onSyncAccept = useCallback((callback: (data: WSSyncAcceptPayload) => void) => {
    const unsub = ws.onSyncAccept(callback as (data: { acceptingDeviceId: string; targetDeviceId: string; timestamp: number }) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

  const onSyncCancel = useCallback((callback: (data: WSSyncCancelPayload) => void) => {
    const unsub = ws.onSyncCancel(callback as (data: { invitingDeviceId: string; acceptedByDeviceId: string; reason?: string }) => void);
    unsubsRef.current.push(unsub);
    return unsub;
  }, [ws]);

   const onSyncReject = useCallback((callback: (data: WSSyncRejectPayload) => void) => {
     const unsub = ws.onSyncReject(callback as (data: { rejectingDeviceId: string; targetDeviceId: string; timestamp: number }) => void);
     unsubsRef.current.push(unsub);
     return unsub;
   }, [ws]);

    // Context value (memoized)
    const value = useMemo<WebSocketContextType>(() => ({
      isConnected: ws.isConnected, // Use synchronous getter for accurate state
      isConnecting: ws.isConnecting,
      connect,
      disconnect,
      send,
      subscribe,
      sendTyping: ws.sendTyping.bind(ws),
      sendMarkRead: ws.sendMarkRead.bind(ws),
      sendMultiDeviceMessage: ws.sendMultiDeviceMessage.bind(ws),
      sendGroupMessage: ws.sendGroupMessage.bind(ws),
      sendSessionSync: ws.sendSessionSync.bind(ws),
      sendMessageRetryRequest: ws.sendMessageRetryRequest.bind(ws),
      onMessage,
      onNewMessage,
      onMessageDelivered,
      onMessageRead,
      onUserOnline,
      onUserOffline,
      onSessionSync,
      onMessageRetry,
      onReadEvent,
      onReadAck,
      onPresence,
      // P2P Sync
      p2pSyncManager: p2pSyncRef.current,
      syncStatus,
      requestSync,
      onSyncRequest,
      onSyncHistory,
      onDeviceOnline,
      // Two-phase sync events
      onSyncInvite,
      onSyncAccept,
      onSyncCancel,
      onSyncReject,
      // Command Bus
      commandBus,
    }), [
      ws.isConnected,
      ws.isConnecting,
      connect,
      disconnect,
      send,
      subscribe,
      ws,
      onMessage,
      onNewMessage,
      onMessageDelivered,
      onMessageRead,
      onUserOnline,
      onUserOffline,
      onSessionSync,
      onMessageRetry,
      onReadEvent,
      onReadAck,
      onPresence,
      syncStatus,
      requestSync,
      onSyncRequest,
      onSyncHistory,
      onDeviceOnline,
      onSyncInvite,
      onSyncAccept,
      onSyncCancel,
      onSyncReject,
      commandBus,
    ]);

  return (
    <WebSocketContext.Provider value={value}>
      {children}
    </WebSocketContext.Provider>
  );
}

// ==================== Hook ====================

export function useWebSocketContext(): WebSocketContextType {
  const context = useContext(WebSocketContext);
  if (!context) {
    throw new Error('useWebSocketContext must be used within WebSocketProvider');
  }
  return context;
}
